In [94]:
import cvxpy as cp
import cvxpy as cp
import numpy as np
import warnings
from scipy.linalg import inv

warnings.filterwarnings("ignore")   

x = cp.Variable(3, nonneg=True)
objective = cp.Minimize(cp.sum(x))

A = np.array([[40, 0, 0],
              [0, 16, 0],
              [0, 0, 12]])

b = np.array([150, 100, 80])
c = np.array([1, 1, 1])

constraints = [A @ x == b, x>=0]

prob = cp.Problem(objective, constraints)
result = prob.solve()

# print out the solution
print("Optimal Values of X", x.value)

# print Basis
print("Basis:", A)
print("B Inverse", inv(A))
print("Optimal Dual Solution", c.T @ inv(A))



Optimal Values of X [3.75       6.25       6.66666667]
Basis: [[40  0  0]
 [ 0 16  0]
 [ 0  0 12]]
B Inverse [[ 0.025       0.         -0.        ]
 [ 0.          0.0625     -0.        ]
 [ 0.          0.          0.08333333]]
Optimal Dual Solution [0.025      0.0625     0.08333333]


In [95]:
# knapsac problem 
x = cp.Variable(3, integer=True)

yt = np.array([0.025, 0.0625, 0.0833])
objective = cp.Maximize(yt.T @ x)

A = np.array([[5, 0, 0],
              [0, 12, 0],
              [0, 0, 16]])

b = np.array([200, 200, 200])
constraints = [A @ x <=b, x>=0]

prob = cp.Problem(objective, constraints)
result = prob.solve()

# print out the solution
print("Optimal Values of X", x.value)
print("Z_bar", 1-(yt.T@x.value))


Optimal Values of X [40. 16. 12.]
Z_bar -1.9996


In [96]:
A = np.array([[40, 0, 0],
              [0, 16, 0],
              [0, 0, 12]])

a_new = np.array([40., 16., 12.]).reshape(3, 1)

newA=np.hstack([a_new, A])
print(newA)

x = cp.Variable(4, nonneg=True)
objective = cp.Minimize(cp.sum(x))

b = np.array([150, 100, 80])
c = np.array([1, 1, 1])

constraints = [newA @ x==b, x>=0]

prob = cp.Problem(objective, constraints)
result = prob.solve()

# print out the solution
print("Optimal Values of X", x.value)

# the optimal solution for x2 is zero so we can drop it
cols = [0, 2, 3]
Basis_Matrix = newA[:, cols]

# print Basis
print("Basis:", Basis_Matrix)
print("B Inverse", inv(Basis_Matrix))
print("Optimal Dual Solution", c.T @ inv(Basis_Matrix))

# knapsac problem 
x = cp.Variable(3, integer=True)

yt = c.T @ inv(Basis_Matrix)
objective = cp.Maximize(yt.T @ x)

A = np.array([[5, 0, 0],
              [0, 12, 0],
              [0, 0, 16]])

b = np.array([200, 200, 200])
constraints = [A @ x <=b, x>=0]

prob = cp.Problem(objective, constraints)
result = prob.solve()

# print out the solution
print("Optimal Values of X", x.value)
print("Z_bar", 1-(yt.T@x.value))
print(prob.solution)







[[40. 40.  0.  0.]
 [16.  0. 16.  0.]
 [12.  0.  0. 12.]]
Optimal Values of X [3.75000000e+00 4.64214789e-11 2.50000000e+00 2.91666667e+00]
Basis: [[40.  0.  0.]
 [16. 16.  0.]
 [12.  0. 12.]]
B Inverse [[ 0.025       0.         -0.        ]
 [-0.025       0.0625     -0.        ]
 [-0.025       0.          0.08333333]]
Optimal Dual Solution [-0.025       0.0625      0.08333333]
Optimal Values of X [-0. 16. 12.]
Z_bar -1.0
Solution(status=optimal, opt_val=2.0, primal_vars={2146: array([-0., 16., 12.])}, dual_vars={}, attr={'solver_specific_stats': {'mip_gap': 0.0}})


In [97]:
# iteration 3
a_new = np.array([0., 16., 12]).reshape(3, 1)
newA = np.hstack([a_new, newA])
print(newA)

x = cp.Variable(5, nonneg=True)
objective = cp.Minimize(cp.sum(x))

b = np.array([150, 100, 80])
c = np.array([1, 1, 1])

constraints = [newA @ x==b, x>=0]

prob = cp.Problem(objective, constraints)
result = prob.solve()

# print out the solution
print("Optimal Values of X", x.value)

cols = [0, 1, 4]
Basis_Matrix = newA[:, cols]

# print Basis
print("Basis:", Basis_Matrix)
print("B Inverse", inv(Basis_Matrix))
print("Optimal Dual Solution", c.T @ inv(Basis_Matrix))

# knapsac problem 
x = cp.Variable(3, integer=True)

yt = c.T @ inv(Basis_Matrix)
objective = cp.Maximize(yt.T @ x)

A = np.array([[5, 0, 0],
              [0, 12, 0],
              [0, 0, 16]])

b = np.array([200, 200, 200])
constraints = [A @ x <=b, x>=0]

prob = cp.Problem(objective, constraints)
result = prob.solve()

# print out the solution
print("Optimal Values of X", x.value)
print("Z_bar", 1-(yt.T@x.value))
print(prob.solution)



[[ 0. 40. 40.  0.  0.]
 [16. 16.  0. 16.  0.]
 [12. 12.  0.  0. 12.]]
Optimal Values of X [2.50000000e+00 3.75000000e+00 1.51497610e-09 2.43920183e-09
 4.16666669e-01]
Basis: [[ 0. 40.  0.]
 [16. 16.  0.]
 [12. 12. 12.]]
B Inverse [[-0.025       0.0625     -0.        ]
 [ 0.025       0.         -0.        ]
 [ 0.         -0.0625      0.08333333]]
Optimal Dual Solution [0.         0.         0.08333333]
Optimal Values of X [-0. -0. 12.]
Z_bar 0.0
Solution(status=optimal, opt_val=1.0, primal_vars={2224: array([-0., -0., 12.])}, dual_vars={}, attr={'solver_specific_stats': {'mip_gap': 0.0}})


In [98]:
Basis_Matrix

array([[ 0., 40.,  0.],
       [16., 16.,  0.],
       [12., 12., 12.]])

In [99]:
2.5 + 3.75 + .41666

6.66666

In [104]:
B = np.array([[20, 0], [1, 1]])
print(B)

print(inv(B))

[[20  0]
 [ 1  1]]
[[ 0.05 -0.  ]
 [-0.05  1.  ]]


In [105]:
B_inv = inv(B)

c = np.array([30, 20])
c1 = np.array([12, 1])

print(c @ B_inv)
print(c1 @ B_inv)

[ 0.5 20. ]
[0.55 1.  ]


In [106]:
c1.shape

(2,)

In [107]:
B.shape

(2, 2)

In [108]:
B_inv @ c1

array([0.6, 0.4])

In [2]:
import pandas as pd

p = r'C:\Users\jaman\OneDrive\CSE6242\class_project\liquidity_master.pkl'

df = pd.read_pickle(p)

df.shape


(37104728, 10)